### ISSUE TITLE
Cyclic dependency with r-future-tests

### ISSUE THREAD

**Issue by wdkrnls** [guix-science/guix-cran-scripts#1]
Running `guix pull` today I ran into this error:

```
(exception %exception (non-self-quoting 140736725401472 "#<&package-cyclic-dependency-error package: #<package r-future-tests@0.7.0 guix-cran/packages/f.scm:984 7fffe8a42790> cycle: (#<package r-future-tests@0.7.0 guix-cran/packages/f.scm:984 7fffe8a42790>)>"))
```

Note that I also saw two warnings at the top of the log file.

```
(repl-version 0 1 1)
Generating package cache for '/gnu/store/nv9lcq76br5yals00921l3jfkq4s2cdl-profile'...
WARNING: (guix-cran packages a): `r-plumber' imported from both (gnu packages cran) and (guix-cran packages p)
WARNING: (guix-cran packages p): `r-swagger' imported from both (gnu packages cran) and (guix-cran packages s)
```

I have attached the full log for your reference.

[hfniqyzgqf1fimwqflqxf79kivgkkl-guix-package-cache.drv.gz](https://github.com/guix-science/guix-cran-scripts/files/11764598/hfniqyzgqf1fimwqflqxf79kivgkkl-guix-package-cache.drv.gz)

**Comment by rekado** [comment]
This must have been a temporary failure.

The warnings are probably due to the fact that importing all CRAN packages can take a little while.  Any packages that have been added to Guix in the meantime may have duplicates in guix-cran.
